from mathics.core.symbols import *
from mathics.core.systemsymbols import *

# TODO: move to system
SymbolGraphics3DBox = Symbol("Graphics3DBox")
SymbolGraphicsBox = Symbol("GraphicsBox")
SymbolGraphicsComplexBox = Symbol("GraphicsComplexBox")
SymbolPolygonBox = Symbol("PolygonBox")
SymbolPolygon3DBox = Symbol("Polygon3DBox")
SymbolLineBox = Symbol("LineBox")
SymbolLine3DBox = Symbol("Line3DBox")
SymbolPointBox = Symbol("PointBox")
SymbolImageSize = Symbol("ImageSize")
SymbolAxes = Symbol("Axes")
SymbolHue = Symbol("Hue")
SymbolAspectRatio = Symbol("AspectRatio")
SymbolAxesStyle = Symbol("AxesStyle")
SymbolBackground = Symbol("Background")
SymbolBoxRatios = Symbol("BoxRatios")
SymbolImageSize = Symbol("ImageSize")
SymbolLabelStyle = Symbol("LabelStyle")
SymbolLighting = Symbol("Lighting")
SymbolPlotRange = Symbol("PlotRange")
SymbolPlotRangePadding = Symbol("PlotRangePadding")
SymbolTicksStyle = Symbol("TicksStyle")
SymbolViewPoint = Symbol("ViewPoint")
SymbolManipulateBox = Symbol("ManipulateBox")
SymbolGridBox = Symbol("System`GridBox")
SymbolManipulate = Symbol("System`Manipulate")
