import csv
import collections

def load(fn):
    result = {}
    with open(fn) as f:
        for i, row in enumerate(csv.reader(f)):
            if i == 0:
                columns = row
            else:
                result[row[0]] = dict(zip(columns, row))
    print(f"{fn}: {len(result)} rows")
    return result

s3 = load("plot-status-3.csv")
s4 = load("plot-status-4.csv")

def compare34():
    print("missing", set(s3.keys()) - set(s4.keys()))
    print("excess", set(s4.keys()) - set(s3.keys()))
#compare34()    

def examples(test_status):
    by_category = collections.defaultdict(lambda: [])
    for name, info in s4.items():
        if test_status(info["Mathics3"]):
            category = info["Category"]
            by_category[category].append(info)
    for category, plots in by_category.items():
        print(category, len(plots))
    return by_category
#examples(lambda status: status != "no")

def by_catgegory(dn, status_test):
    implemented = examples(status_test)
    for category, plots in implemented.items():
        fn = f"{dn}/{category}.m3d"
        with open(fn, "w") as f:
            for plot in plots:
                print("<!-- this file is automatically generated -->")
                print(plot["Function"], file=f)
                print("```", file=f)
                print(plot["Example"], file=f)
                print("```", file=f)
#make_implementeds("../data/survey", lambda status: status != "no")

def unified(fn, status_test):
    implemented = examples(status_test)
    fn = f"../data/survey/unimplemented.m3d"
    with open(fn, "w") as f:
        print("<!-- this file is automatically generated -->", file=f)
        for category, plots in implemented.items():
            print(f"\n### {category}\n", file=f)
            for plot in plots:
                print(plot["Function"], file=f)
                print("```", file=f)
                print(plot["Example"], file=f)
                print("```", file=f)
unified("../data/unimplemented", lambda status: status == "no")

