import csv
import collections
import subprocess
import os

def load(fn):
    result = {}
    with open(fn) as f:
        for i, row in enumerate(csv.reader(f)):
            if i == 0:
                columns = row
            else:
                result[row[0]] = dict(zip(columns, row))
    print(f"{fn}: {len(result)} rows")
    return result

def save(fn, fieldnames, data_dicts):
    with open(fn, "w") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(data_dicts)

s3 = load("plot-status-3.csv")
s4 = load("plot-status-4.csv")
s5 = load("plot-status-5.csv")

def compare34():
    print("missing", set(s3.keys()) - set(s4.keys()))
    print("excess", set(s4.keys()) - set(s3.keys()))
#compare34()    

def examples(test_status, csv=s5, field="Git"):
    by_category = collections.defaultdict(lambda: [])
    for name, info in csv.items():
        if test_status(info[field]):
            category = info["Category"]
            by_category[category].append(info)
    for category, plots in by_category.items():
        print(category, len(plots))
    return by_category
#examples(lambda status: status != "no")

def make5():

    # find which are in git
    git = set()
    cd = os.getcwd()
    os.chdir("/Users/bdlucas1/mathics-core")
    for name, info in s3.items():
        rc = subprocess.run(["git", "grep", "class " + name, "mathics"])
        if rc.returncode == 0:
            git.add(name)
    os.chdir(cd)

    
    # add examples from s4, if available
    # and add "Git" column based on checking repo
    for name, info in s3.items():
        if name in s4:
            info |= s4[name]
        info["Git"] = "yes" if name in git else "no"

    # write it
    fieldnames = ["Function", "Mathics3", "Git", "Category", "Example"]
    print("cd", cd, "cwd", os.getcwd())
    save("plot-status-5.csv", fieldnames, s3.values())

###make5()


def print_plots(plots, f):
    for plot in plots:
        name = plot["Function"]
        print(name, file=f)
        print(f"``` m3d test:{name}", file=f)
        print(plot["Example"], file=f)
        print("```", file=f)


def by_category(dn, status_test):
    implemented = examples(status_test)
    for category, plots in implemented.items():
        fn = f"{dn}/{category}.m3d"
        with open(fn, "w") as f:
            print("<!-- this file is automatically generated -->")
            print_plots(plots, f)
by_category("../data/survey", lambda status: status != "no")

def unified(fn, status_test):
    implemented = examples(status_test)
    fn = f"../data/survey/unimplemented.m3d"
    with open(fn, "w") as f:
        print("<!-- this file is automatically generated -->", file=f)
        print("<!-- m3d autorun:off -->", file=f)
        for category, plots in implemented.items():
            print(f"\n### {category}\n", file=f)
            print_plots(plots, f)
unified("../data/unimplemented", lambda status: status == "no")

